[project]
name = "ivoryos-edge"
version = "0.1.0"
description = "IvoryOS Edge Server"
requires-python = ">=3.9"
dependencies = [
    "fastapi",
    "uvicorn",
    "python-socketio[client]",
    "pydantic",
    "python-dotenv",
    "aiohttp",
    "sqlalchemy",
    "aiosqlite",
    "paho-mqtt"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-asyncio",
    "httpx"
]
